version: "3.4"

services:
  redis1:
    image: redis:6.0.8
    restart: "no"
    container_name: redis-node-1
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /mnt/data/rediscluster/6381/data:/data
      - /mnt/data/rediscluster/6381/conf/redis.conf:/etc/redis/redis.conf
    network_mode: "host"

  redis2:
    image: redis:6.0.8
    restart: "no"
    container_name: redis-node-2
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /mnt/data/rediscluster/6382/data:/data
      - /mnt/data/rediscluster/6382/conf/redis.conf:/etc/redis/redis.conf
    network_mode: "host"

  redis3:
    image: redis:6.0.8
    restart: "no"
    container_name: redis-node-3
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /mnt/data/rediscluster/6383/data:/data
      - /mnt/data/rediscluster/6383/conf/redis.conf:/etc/redis/redis.conf
    network_mode: "host"

  redis4:
    image: redis:6.0.8
    restart: "no"
    container_name: redis-node-4
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /mnt/data/rediscluster/6384/data:/data
      - /mnt/data/rediscluster/6384/conf/redis.conf:/etc/redis/redis.conf
    network_mode: "host"

  redis5:
    image: redis:6.0.8
    restart: "no"
    container_name: redis-node-5
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /mnt/data/rediscluster/6385/data:/data
      - /mnt/data/rediscluster/6385/conf/redis.conf:/etc/redis/redis.conf
    network_mode: "host"

  redis6:
    image: redis:6.0.8
    restart: "no"
    container_name: redis-node-6
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /mnt/data/rediscluster/6386/data:/data
      - /mnt/data/rediscluster/6386/conf/redis.conf:/etc/redis/redis.conf
    network_mode: "host"