server:
  port: 8080

spring:
  data:
    redis:
      cluster:
        nodes: 101.200.157.190:6381,101.200.157.190:6382,101.200.157.190:6383,101.200.157.190:6384,101.200.157.190:6385,101.200.157.190:6386
        max-redirects: 3 # 获取失败 最大重定向次数
      password: 123456
      lettuce:
        cluster:
          refresh:
            adaptive: true #支持集群拓扑动态感应刷新，自适应拓扑刷新是否使用所有可用的更新，默认false关闭
            period: 2000  #定时刷新
        pool:
          max-active: 8 #连接池最大连接数(使用负值表示没有限制)
          max-wait: -1 #最大阻塞等待时间(使用负值表示没有限制)
          max-idle: 8 #最大空闲连接数
          min-idle: 0 #最小空闲连接数

