spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot3_test?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initial-size: 20
    max-idle: 60
    max-wait: 10000
    min-idle: 10
    max-active: 200

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.cyk.springboot3.poi.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

###显示SQL语句部分
logging.level.com.cyk.springboot3.poi.mapper: debug