#server:
#  port: 8080
#
#spring:
#  data:
#    redis:
#      host: 101.200.157.190
#      port: 7379
#      password:
#      lettuce:
#        pool:
#          max-active: 8 #连接池最大连接数(使用负值表示没有限制)
#          max-wait: -1 #最大阻塞等待时间(使用负值表示没有限制)
#          max-idle: 8 #最大空闲连接数
#          min-idle: 0 #最小空闲连接数

# 以上主从模式配置
# 以下哨兵模式配置
spring:
  data:
    redis:
      password :                             # Redis服务器连接密码（默认为空）
      timeout : 2000                         # 连接超时时间（毫秒）
      pool:
        maxActive : 600                      # 连接池最大连接数（使用负值表示没有限制）
        maxWait : 1000                       # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxIdle : 300                        # 连接池中的最大空闲连接
        minIdle : 0                           # 连接池中的最小空闲连接
      sentinel:
        master: mymaster           #对应sentinel
        nodes: 101.200.157.190:27379,101.200.157.190:27380,101.200.157.190:27381  # sentinel节点信息