package com.cyk.springboot3.poi.mapper;

import com.cyk.springboot3.poi.entity.BootUser;

import java.util.List;

public interface BootUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated
     */
    int insert(BootUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated
     */
    int insertSelective(BootUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated
     */
    BootUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BootUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BootUser record);


    List<BootUser> list();
}