server:
  port: 8080

# 配置swagger文档的访问路径，访问地址：http://127.0.0.1:8080/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      #exclude: WEB-INF/**

  datasource:
    url: jdbc:mysql://localhost:3306/springboot3_test?useSSL=false&autoReconnect=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initial-size: 20
    max-idle: 60
    max-wait: 10000
    min-idle: 10
    max-active: 200

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      lettuce:   #jedis:  ## 切换 redis 客户端
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.cyk.springboot3.redis.lettuce.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

